apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: low-latency-pvc
  annotations:
    # Set IOPS between 3,000 and 64,000
    ibm.io/iops: "64000"
    # Set throughput between 125 and 1024 (MBps)
    ibm.io/throughput: "1024"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: ibmc-vpc-block-sdp
