apiVersion: v1
kind: ConfigMap
metadata:
  name: openmetrics-pmlogconf-configmap
  namespace: llm-d-pfc-cpu
data:
  vllm: "#pmlogconf-setup 2.0\nident   vLLM metrics from openmetrics PMDA\nforce   include\n\topenmetrics.vllm\n"
  dcgm: "#pmlogconf-setup 2.0\nident   DCGM metrics from openmetrics PMDA\nforce   include\n\topenmetrics.dcgm\n"
