apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-nfs
  namespace: llm-d-batch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: nfs-rwx
