apiVersion: v1
kind: ServiceAccount
metadata:
  name: pcp
  namespace: llm-d-batch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pcp-privileged-llm-d-batch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: pcp
  namespace: llm-d-batch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guidellm
  namespace: llm-d-batch
