# DataScienceClusterInitialization - must be created before the DataScienceCluster.
# Using RawDeployment for kserve so ServiceMesh/Istio is not required.
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
  serviceMesh:
    managementState: Removed
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
